# Generated by Django 3.1.1 on 2020-09-11 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Matches',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
                ('analysis', models.TextField()),
                ('stats', models.TextField()),
                ('choose11', models.TextField()),
                ('explanation', models.TextField()),
            ],
        ),
    ]
