# Generated by Django 3.1.1 on 2020-09-11 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matches',
            name='analysis',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='matches',
            name='choose11',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='matches',
            name='explanation',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='matches',
            name='stats',
            field=models.TextField(null=True),
        ),
    ]
