# Generated by Django 3.1.1 on 2020-09-11 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_matches_display'),
    ]

    operations = [
        migrations.CreateModel(
            name='Update',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updatecsk', models.TextField(blank=True, null=True)),
                ('updatercb', models.TextField(blank=True, null=True)),
                ('updatemi', models.TextField(blank=True, null=True)),
                ('updatekkr', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
