# Generated by Django 3.1.1 on 2020-09-11 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='update',
            name='bigbreaking',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
