# Generated by Django 3.1.1 on 2020-09-11 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_update_bigbreaking'),
    ]

    operations = [
        migrations.AddField(
            model_name='update',
            name='timestamp',
            field=models.DateTimeField(null=True),
        ),
    ]
