# Generated by Django 3.1.1 on 2020-09-12 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='update',
            name='timestamp',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
