# Generated by Django 3.1.1 on 2020-09-13 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20200912_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='matches',
            name='matchnumber',
            field=models.IntegerField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
